[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kontext-super-prompt"
version = "1.2.1"
description = "Intelligent Visual Prompt Builder for Flux Kontext - ComfyUI Custom Node"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
authors = [
    {name = "Kontext Team", email = "kontext@example.com"}
]
maintainers = [
    {name = "Kontext Team", email = "kontext@example.com"}
]
keywords = ["comfyui", "flux", "kontext", "visual-prompt", "ai", "image-editing", "annotation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Multimedia :: Graphics :: Graphics Conversion",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "numpy>=1.21.0",
    "pillow>=9.0.0",
]

[project.optional-dependencies]
ollama = ["ollama>=0.4.8"]
opencv = ["opencv-python>=4.5.0"]
nlp = ["transformers>=4.20.0"]
diffusion = ["diffusers>=0.20.0"]
web = ["aiohttp>=3.8.0"]
data = ["pandas>=1.3.0", "openpyxl>=3.0.0"]
all = [
    "ollama>=0.4.8",
    "opencv-python>=4.5.0",
    "transformers>=4.20.0",
    "diffusers>=0.20.0",
    "aiohttp>=3.8.0",
    "pandas>=1.3.0",
    "openpyxl>=3.0.0",
]

[project.urls]
Homepage = "https://github.com/aiaiaikkk/kontext-super-prompt"
Repository = "https://github.com/aiaiaikkk/kontext-super-prompt"
Documentation = "https://github.com/aiaiaikkk/kontext-super-prompt#readme"
"Bug Reports" = "https://github.com/aiaiaikkk/kontext-super-prompt/issues"
"Source Code" = "https://github.com/aiaiaikkk/kontext-super-prompt"
Changelog = "https://github.com/aiaiaikkk/kontext-super-prompt/releases"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
exclude = ["tests*", "docs*", "examples*", "__pycache__*", "*.pyc"]

[tool.setuptools.package-data]
"*" = ["*.js", "*.html", "*.css", "*.png", "*.jpg", "*.json", "*.md", "*.txt", "*.xlsx"]