[project]
name = "KontextVisualPromptWindow_Intelligent"
version = "1.2.0"
description = "Intelligent Visual Prompt Builder for Flux Kontext - Advanced image editing, visual annotation recognition, and structured prompt generation"
authors = [
    {name = "Kontext Team", email = "contact@kontext.ai"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
keywords = ["comfyui", "flux", "kontext", "visual-prompt", "image-editing", "ai"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9", 
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Multimedia :: Graphics :: Graphics Conversion",
]

dependencies = [
    "torch>=1.13.0",
    "torchvision>=0.14.0",
    "numpy>=1.21.0",
    "pillow>=8.3.0",
    "opencv-python>=4.5.0",
]

[project.optional-dependencies]
full = [
    "transformers>=4.21.0",
    "diffusers>=0.20.0",
    "requests>=2.25.0",
    "aiohttp>=3.8.0",
]

dev = [
    "pytest>=6.0.0",
    "black>=22.0.0",
    "flake8>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/aiaiaikkk/kontext-super-prompt"
Repository = "https://github.com/aiaiaikkk/kontext-super-prompt"
Documentation = "https://github.com/aiaiaikkk/kontext-super-prompt/blob/main/README.md"
"Bug Reports" = "https://github.com/aiaiaikkk/kontext-super-prompt/issues"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nodes", "web"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.js", "*.json", "*.xlsx", "*.png", "*.md"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"